---
name: Label Checker
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check Required labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          all_of: status/on-call-review-complete
          none_of: status/on-call-review-needed
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  check_text_labels:
    name: Check Text labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: status/text-review-complete,status/no-text-review-needed
          none_of: status/text-review-needed
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  check_hold_labels:
    name: Check Holding Labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          none_of: status/on-hold,status/future-release
          repo_token: ${{ secrets.GITHUB_TOKEN }}
