name: Rust
on:
  push:
    paths:
      - "rust_dev_preview/**"
    branches:
      - main
  pull_request:
    paths:
      - "rust_dev_preview/**"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pre-setup
        run: sudo apt-get update && sudo apt-get install -y libclang-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.66.1"
          override: true
          components: clippy, rustfmt
      - uses: actions-rs/cargo@v1
        name: cargo check
        with:
          command: check
          args: --manifest-path rust_dev_preview/Cargo.toml --all-targets
      - uses: actions-rs/cargo@v1
        if: success() || failure()
        name: cargo fmt
        with:
          command: fmt
          args: --manifest-path rust_dev_preview/Cargo.toml --all --check
      - uses: actions-rs/cargo@v1
        if: success() || failure()
        name: cargo clippy
        with:
          command: clippy
          args: --manifest-path rust_dev_preview/Cargo.toml -- -D warnings
      - uses: actions-rs/cargo@v1
        if: success() || failure()
        name: cargo test
        with:
          command: test
          args: --manifest-path rust_dev_preview/Cargo.toml
        env:
          APP_ENVIRONMENT: test
